### ISSUE TITLE
Rhino Issue: Using non-EN models, builtins return "plain text" instead of parsed output

### ISSUE THREAD

**Issue by tsileo** [Picovoice/rhino#271]
Hey!

### Expected behaviour

Using the library with the french model, and using this expression `[change, ajuste, modifie, règle] (la luminosité de) la lumière (du, de) $room:room à $pv.Percent:pct`, the inference returns the percentage in "plain text":
```
Inference(is_understood=True, intent='lum', slots={'room': 'salon', 'pct': 'cinquante pour cent'})
```

### Actual behaviour

According to the doc (https://picovoice.ai/docs/tips/syntax-cheat-sheet/), I expect the inference to be:

```
Inference(is_understood=True, intent='lum', slots={'room': 'salon', 'pct': '50%'})
```

### Steps to reproduce the behaviour

Create any expression in french, using a `pv.Percent` slot type.

I am using the Python client, but the web console behaves in the same way.

Thanks!

**Comment by tsileo** [comment]
I also noticed that others built-in slot types, like `pv.SingleDigitInteger`, share the same behavior (returning digits as plain-text).

**Comment by safsoun** [comment]
Same Here, I found the same issue with pv.TwoDigitInteger.
I've opened this ticket #272 before I perceive this ticket is already submitted.

**Comment by ErisMik** [comment]
This issue has been addressed and will be included in the `v2.1` release of Rhino which should be coming in the following few weeks.

**Comment by ErisMik** [comment]
With the release of `v2.1` today, this issue has been resolved.

**Comment by safsoun** [comment]
Hello,

Unfortunately, it was not fixed .. I'm still having plain text: "vingt cinq" for 25.
I'm using mcu platform (STM32).

**Comment by ErisMik** [comment]
Are you certain you are using the latest version of the picovoice library? What is the output of the `pv_picovoice_version()` function?

**Comment by safsoun** [comment]
pv_picovoice_version() output is 2.1.0.
I've downloaded the zip of picovoice package yesterday and re-trained the model and had plain text!

**Comment by ErisMik** [comment]
What specific device are you using?

**Comment by safsoun** [comment]
I'm using STM32F769I-DISCO board

**Comment by mrrostam** [comment]
As discussed in #272 the issue is fixed and I closed the issue
